### ISSUE TITLE
List of all endpoints

### ISSUE THREAD

**Issue by triplecookedchips** [davefojtik/RunPod-Fooocus-API#13]
Hello!

Is it possible to get a full list of endpoints? or where can I find these? I need to access some of the advanced features, such as changing the deionising strength etc

Thanks

**Comment by davefojtik** [comment]
Hello. The list is in [handler.py](https://github.com/davefojtik/RunPod-Fooocus-API/blob/NetworkVolume/src/handler.py) or [Fooocus-API docs](https://github.com/mrhan1993/Fooocus-API/blob/f5b2f68ac2ed139692f8974c3fb0526aa9a77ec3/docs/api_doc_en.md), but it's true I might also add it to our docs.
Although denoising strength is [advanced param](https://github.com/mrhan1993/Fooocus-API/blob/f5b2f68ac2ed139692f8974c3fb0526aa9a77ec3/docs/api_doc_en.md?plain=1#L920) in payload, not an endpoint. You can use it like this for vary, upscale and inpaint:
```json
{
    "input":{
        "api_name":"your-endpoint",
        "prompt":"your-prompt",
        "require_base64": true

        "advanced_params":{
          "overwrite_vary_strength":-0.5,
          "overwrite_upscale_strength":1,
          "inpaint_strength":0.2
        }
    }
}
```
And for img2img the denoising is basically "cn_weight":
```json
{
    "input":{
        "api_name":"img2img2",
        "prompt":"your-prompt",
        "image_prompts":[
            {
                "cn_img":"url-or-base64",
                "cn_stop":0.5,
                "cn_weight":1,
                "cn_type":"ImagePrompt"
            }
        ],
        "require_base64": true
    }
}
```
Don't hesitate to ask if there's anything else I can help you with.

**Comment by triplecookedchips** [comment]
this is so helpful, thank you. The only option I cannot seem to find is the 'method' for inpainting. When using the local version you have the choice to 'inpaint or outpaint', 'improve details' or 'modify content' - do you know how I can do this?
thanks!!
<img width="457" alt="Screenshot 2024-03-23 at 16 29 46" src="https://github.com/davefojtik/RunPod-Fooocus-API/assets/79034778/a1f960a4-79c5-43c9-8b09-f7e1d1730394">

**Comment by davefojtik** [comment]
Unfortunately I don't see this exact setting implemented in Fooocus-API, but based on the [code](https://github.com/lllyasviel/Fooocus/blob/e2f9bcb11d06216d6800676c48d8d74d6fd77a4b/webui.py#L598) of local Fooocus and how that setting works, you could do the same with changing `inpaint_additional_prompt` (with prompts like this:
```python
default_value=[
        'highly detailed face', 'detailed girl face', 'detailed man face', 'detailed hand', 'beautiful eyes'
    ]
```
), then `inpaint_disable_initial_latent`, `inpaint_engine`, `inpaint_strength` and `inpaint_respective_field`.

These seem to be the settings that dropdown selection changes. We can also see the individual values that they use in the source code:
```python
# Improve Detail
if mode == modules.flags.inpaint_option_detail:
    return [
        gr.update(visible=True), gr.update(visible=False, value=[]),
        gr.Dataset.update(visible=True, samples=modules.config.example_inpaint_prompts),
        False, 'None', 0.5, 0.0
    ]
# Modify Content
if mode == modules.flags.inpaint_option_modify:
    return [
        gr.update(visible=True), gr.update(visible=False, value=[]),
        gr.Dataset.update(visible=False, samples=modules.config.example_inpaint_prompts),
        True, modules.config.default_inpaint_engine_version, 1.0, 0.0
    ]
# Inpaint or Outpaint
return [
    gr.update(visible=False, value=''), gr.update(visible=True),
    gr.Dataset.update(visible=False, samples=modules.config.example_inpaint_prompts),
    False, modules.config.default_inpaint_engine_version, 1.0, 0.618
]
```
Where samples are examples for `inpaint_additional_prompt`, the True or False value should be `inpaint_disable_initial_latent`, 'None' or inpaint_engine_version is `inpaint_engine`, and the last two values should be `inpaint_strength` and `inpaint_respective_field`.

So it is achievable by a bit of custom code in your app that would change these payload params based on what you want to do. Or if you would want to have it implemented in the API itself, I can try to push it into the Fooocus-API code or our repo in the next updates.

**Comment by triplecookedchips** [comment]
legend. For me, actually it isn't necessary to have them as presets, I can just tweak the parameters you mentioned. Great job with this! really appreciate the work

**Comment by davefojtik** [comment]
Inpaint presets feature merged with the new update. Closing this issue as completed. Thanks for your feedback!
