### ISSUE TITLE
Failed at running NetworkVolume Pod

### ISSUE THREAD

**Issue by mingekko** [davefojtik/RunPod-Fooocus-API#19]
Hi there!

I've tried to deploy the NetworkVolume branch to RunPod - but i got an error after deploying the Network Volume Pod.

Steps:

1. Building a custom volume image - ( add some extra loras and models to the networksetup.sh )
2. Set latest tag to the builded docker image
3. Push to Docker Hub
4. Creating a template at RunPod ( Container Disk: 50gb, Expose HTTP Ports: default, Expose TCP Ports: default )
5. Add new network volume ( Size: 50gb )
6. Deploy network volume ( template: my own template which i've created at 4. step )
7. Docker container started
8. Got error: [FATAL tini (7)] exec /bin/sh failed: Exec format error

Can anyone help to resolve this issue? I think i've made a mistake one of steps but i cant  figure out where.

Thanks!

**Comment by davefojtik** [comment]
Any chance you're building the image on ARM processor? Please make sure you see "amd64" as "Architecture" when running `docker inspect your-image`

**Comment by mingekko** [comment]
> Any chance you're building the image on ARM processor? Please make sure you see "amd64" as "Architecture" when running `docker inspect your-image`

Ohh yess, that was the problem! Thank you very much!
