### ISSUE TITLE
Switching from juggernaut to different model

### ISSUE THREAD

**Issue by piptyltd** [davefojtik/RunPod-Fooocus-API#24]
Tried to change from juggernaut to dreamshaper, editted the Dockerfile on Standalone branch to download the new model as well as adjusted the default config, however when trying to call the endpoint I'm seeing the below errors:

WARNING [Warning] Wrong base_model_name input: DreamShaperXL_Turbo_v2.safetensors, using default

ERROR [Task Queue] Import default pipeline error: [Errno 18] Invalid cross-device link: '/workspace/repositories/Fooocus/models/checkpoints/DreamShaperXL_Turbo_v2.safetensors' -> '/workspace/repositories/Fooocus/models/checkpoints/DreamShaperXL_Turbo_v2.safetensors.corrupted'

I already have 

"default_model": "DreamShaperXL_Turbo_v2.safetensors",

In default.json.

Am I missing something?

**Comment by davefojtik** [comment]
Having a .corrupted file suggests there's a problem with your model file. Can you please share more information about how you bake it into the image? 
- Did you use wget or local copy?
   - if wget, did you correctly specify the final file name with the -O flag and the same one in the default.json? 
   `RUN wget -P /workspace/repositories/Fooocus/models/checkpoints/ -O yourmodelname.safetensors https://civitai.com/api/download/models/333449`
   - if wget, did the file download successfully? (observed in the build log)
- Where did you download the model from?
- Did you specify the `base_model_name` param in the payload? (_you don't have to when you set it in default.json and plan to use only one_)

I tested the mentioned model by downloading it from [civit.ai](https://civitai.com/models/112902?modelVersionId=333449) and doing:
```dockerfile
# Dockerfile
COPY models/dreamshaperXL_v2TurboDPMSDE.safetensors /workspace/repositories/Fooocus/models/checkpoints/dreamshaperXL_v2TurboDPMSDE.safetensors
```
```javascript
// default.json
"default_model": "dreamshaperXL_v2TurboDPMSDE.safetensors",
```
and it works just fine so I can't seem to reproduce it this way.

**Comment by piptyltd** [comment]
Thanks for the response @davefojtik 
- Used wget
wget -P /workspace/repositories/Fooocus/models/checkpoints/DreamShaperXL_Turbo_v2.safetensors https://huggingface.co/Lykon/dreamshaper-xl-v2-turbo/resolve/main/DreamShaperXL_Turbo_v2.safetensors?download=true
- download was successful, however I can try to use the local copy
- did not specify `base_model_name`, used default.json instead
I'll give the local copy a try, maybe that'll ensure better integrity of dependencies

**Comment by davefojtik** [comment]
> Used wget
wget -P /workspace/repositories/Fooocus/models/checkpoints/DreamShaperXL_Turbo_v2.safetensors https://huggingface.co/Lykon/dreamshaper-xl-v2-turbo/resolve/main/DreamShaperXL_Turbo_v2.safetensors?download=true

While this `wget` format is valid, when I used it like that in the past, I had problems too. One of the [differences](https://stackoverflow.com/questions/16678487/how-to-change-filename-of-a-file-downloaded-with-wget) is yours keeps the file name of the source, not the one you specify, which can cause problems even when it seems the same. Try the one commented in the dockerfile or how I wrote it in the previous response (_with the -O flag_), and perhaps this little change will solve the problem.
```dockerfile
RUN wget -P /workspace/repositories/Fooocus/models/checkpoints/ -O DreamShaperXL_Turbo_v2.safetensors https://huggingface.co/Lykon/dreamshaper-xl-v2-turbo/resolve/main/DreamShaperXL_Turbo_v2.safetensors?download=true
```

**Comment by piptyltd** [comment]
> > Used wget
> > wget -P /workspace/repositories/Fooocus/models/checkpoints/DreamShaperXL_Turbo_v2.safetensors https://huggingface.co/Lykon/dreamshaper-xl-v2-turbo/resolve/main/DreamShaperXL_Turbo_v2.safetensors?download=true
> 
> While this `wget` format is valid, when I used it like that in the past, I had problems too. One of the [differences](https://stackoverflow.com/questions/16678487/how-to-change-filename-of-a-file-downloaded-with-wget) is yours keeps the file name of the source, not the one you specify, which can cause problems even when it seems the same. Try the one commented in the dockerfile or how I wrote it in the previous response (_with the -O flag_), and perhaps this little change will solve the problem.
> 
> ```dockerfile
> RUN wget -P /workspace/repositories/Fooocus/models/checkpoints/ -O DreamShaperXL_Turbo_v2.safetensors https://huggingface.co/Lykon/dreamshaper-xl-v2-turbo/resolve/main/DreamShaperXL_Turbo_v2.safetensors?download=true
> ```

When I try that the container cant seem to find the file, the whole `/workspace/` does not exist for some reason

**Comment by davefojtik** [comment]
I see now. It does not behave correctly even when creating the folders in advance. I probably broke it again when I changed it to a separate stage in the previous updates. The wget way was always problematic, that's why I use the local COPY when publishing these images.

I'll try to fix it ASAP. Thanks for pointing this out.
