### ISSUE TITLE
Error using img2img and img2img2

### ISSUE THREAD

**Issue by samuelgdc** [davefojtik/RunPod-Fooocus-API#6]
Hi, I deploy to runpod following the instructions and everything was working great using text2img.

Now I wanted to try img2img2 and I get this error:

{
    "delayTime": 1475,
    "error": "{\"error_type\": \"<class 'requests.exceptions.JSONDecodeError'>\", \"error_message\": \"Expecting value: line 1 column 1 (char 0)\", \"error_traceback\": \"Traceback (most recent call last):\\n  File \\\"/usr/local/lib/python3.10/dist-packages/requests/models.py\\\", line 971, in json\\n    return complexjson.loads(self.text, **kwargs)\\n  File \\\"/usr/lib/python3.10/json/__init__.py\\\", line 346, in loads\\n    return _default_decoder.decode(s)\\n  File \\\"/usr/lib/python3.10/json/decoder.py\\\", line 337, in decode\\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\\n  File \\\"/usr/lib/python3.10/json/decoder.py\\\", line 355, in raw_decode\\n    raise JSONDecodeError(\\\"Expecting value\\\", s, err.value) from None\\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"/usr/local/lib/python3.10/dist-packages/runpod/serverless/modules/rp_job.py\\\", line 115, in run_job\\n    handler_return = handler(job)\\n  File \\\"/handler.py\\\", line 122, in handler\\n    json = run_inference(event[\\\"input\\\"])\\n  File \\\"/handler.py\\\", line 112, in run_inference\\n    return response.json()\\n  File \\\"/usr/local/lib/python3.10/dist-packages/requests/models.py\\\", line 975, in json\\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\\nrequests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\\n\", \"hostname\": \"7d0txlvt1swiiw-64410dbd\", \"worker_id\": \"7d0txlvt1swiiw\", \"runpod_version\": \"1.3.4\"}",
    "executionTime": 95,
    "id": "3bba9ed8-af89-4e77-b93b-0dd5210df0f7-u1",
    "status": "FAILED"
}

![image](https://github.com/davefojtik/RunPod-Fooocus-API/assets/69766050/3e8bc67e-7a1b-4339-8e89-4401023fa367)

What might be the reason?

I sent a test base64 image:
//rest of body
"image_prompts": [
    {
        "cn_img": "iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAIAAADTED8xAAADMElEQVR4nOzVwQnAIBQFQYXff81RUkQCOyDj1YOPnbXWPmeTRef+/3O/OyBjzh3CD95BfqICMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMO0TAAD//2Anhf4QtqobAAAAAElFTkSuQmCC",
        "cn_stop": 0.9,
        "cn_weight": 0.85,
        "cn_type": "FaceSwap"
    }
]

Thank you

**Comment by davefojtik** [comment]
If the **_exact_** example above doesn't work:

- Double check you're using `3wad/runpod-fooocus-api:0.2.4` on the endpoint or your custom image is built with the current up-to-date code from this repo.
- Try to send the request with something like Postman or similar API clients/IDE extensions to eliminate errors in the used language or your application
- Double check that the format of your Url-safe Base64 image is the same or similar to the one we both used in examples. I don't see the whole error, but the 2nd and 4th line from the bottom on the last screenshot can sometimes guide where one should look at least a bit. In this case `AttributeError: 'NoneType' object has no attribute 'file'` is a problem with the input image based on previous lines stating `..img/utils.py, .. in read_input_image`

To assist you better or reproduce your enviroment, I would need to know what and how is your data being send. Feel free to to post more info about your app here, or if you don't want it public we can talk via [Email](mailto:dave@qode.cc?subject=[GitHub]%20Error%20using%20img2img) or [Discord](https://discord.com/users/675731846889209882)

**Comment by samuelgdc** [comment]
> If the **_exact_** example above doesn't work:
> 
> * Double check you're using `3wad/runpod-fooocus-api:0.2.4` on the endpoint or your custom image is built with the current up-to-date code from this repo.
> * Try to send the request with something like Postman or similar API clients/IDE extensions to eliminate errors in the used language or your application
> * Double check that the format of your Url-safe Base64 image is the same or similar to the one we both used in examples. I don't see the whole error, but the 2nd and 4th line from the bottom on the last screenshot can sometimes guide where one should look at least a bit. In this case `AttributeError: 'NoneType' object has no attribute 'file'` is a problem with the input image based on previous lines stating `..img/utils.py, .. in read_input_image`
> 
> To assist you better or reproduce your enviroment, I would need to know what and how is your data being send. Feel free to to post more info about your app here, or if you don't want it public we can talk via [Email](mailto:dave@qode.cc?subject=%5BGitHub%5D%20Error%20using%20img2img) or [Discord](https://discord.com/users/675731846889209882)

Thanks for the help, I sent you an email

**Comment by solarbotanist** [comment]
Amazing work so far, thank you. So, it's definitely a bug in Fooocus API? struggling with the same issue and get the same result with the shared json in postman...

**Comment by davefojtik** [comment]
@solarbotanist 
Yes, the issue appeared in new versions and it's discussed here: https://github.com/konieshadow/Fooocus-API/issues/149, most likely fixed in the next release/docker image.

Use `konieshadow/fooocus-api:v0.3.26` (_or in future updates, the version specified in the readme_) on the network volume. I can't guarantee compatibility with the latest versions because of possible breaking changes. The Fooocus-API version compatibility gets updated here only once I thoroughly test it in production on our Discord server bot.

**Comment by solarbotanist** [comment]
> @solarbotanist Yes, the issue appeared in new versions and it's discussed here: [konieshadow/Fooocus-API#149](https://github.com/konieshadow/Fooocus-API/issues/149), most likely fixed in the next release/docker image.
> 
> Use `konieshadow/fooocus-api:v0.3.26` (_or in future updates, the version specified in the readme_) on the network volume. I can't guarantee compatibility with the latest versions because of possible breaking changes. The Fooocus-API version compatibility gets updated here only once I thoroughly test it in production on our Discord server bot.

This did the trick for me. Thanks for responding!
