### ISSUE TITLE
Inpaint issue

### ISSUE THREAD

**Issue by kirrr21** [davefojtik/RunPod-Fooocus-API#7]
Hi David! Thank you for your work.
i have problems with inpainting with mask, tried everything.
Outpainting works fine, but when i do inpainting with mask, i just get whole new image instead of edited image.
When i tried inpainting with mask in this step "After the Juggernaut model is downloaded, use the connect button to load into the Fooocus-API docs running on the pod's 8888 port. Here you should try all the API methods you plan to use. Not only to verify they work, but also additional models are downloaded once you run inpaint, outpaint, upscale, vary and image inputs (canny, face swap etc.) endpoints for the first time." inpainting with mask worked as expected. But now when i try to do it with api with same images using your request example, i have this issue.

my payload looks like this :
{
    "input":{
        "api_name": "inpaint-outpaint", 
        "input_image": "/9j/4AAQSkZJRgABAQAASABIAAD/4U0wRXhpZgAA..."
        "input_mask:": "/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAQDAwQDAwQE...",
        "inpaint_additional_prompt": "my prompt",
        "require_base64": "true"
    }

as result i get complete new image.
if i add outpaint paramaters to it, outpainting works correctly.

if i change inpaint-outpaint to inpaint-outpaint2
i have error
{
    "delayTime": 5247,
    "error": "{\"error_type\": \"<class 'requests.exceptions.JSONDecodeError'>\", \"error_message\": \"Expecting value: line 1 column 1 (char 0)\", \"error_traceback\": \"Traceback (most recent call last):\\n  File \\\"/usr/local/lib/python3.10/dist-packages/requests/models.py\\\", line 971, in json\\n    return complexjson.loads(self.text, **kwargs)\\n  File \\\"/usr/lib/python3.10/json/__init__.py\\\", line 346, in loads\\n    return _default_decoder.decode(s)\\n  File \\\"/usr/lib/python3.10/json/decoder.py\\\", line 337, in decode\\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\\n  File \\\"/usr/lib/python3.10/json/decoder.py\\\", line 355, in raw_decode\\n    raise JSONDecodeError(\\\"Expecting value\\\", s, err.value) from None\\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"/usr/local/lib/python3.10/dist-packages/runpod/serverless/modules/rp_job.py\\\", line 115, in run_job\\n    handler_return = handler(job)\\n  File \\\"/handler.py\\\", line 122, in handler\\n    json = run_inference(event[\\\"input\\\"])\\n  File \\\"/handler.py\\\", line 112, in run_inference\\n    return response.json()\\n  File \\\"/usr/local/lib/python3.10/dist-packages/requests/models.py\\\", line 975, in json\\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\\nrequests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\\n\", \"hostname\": \"xv24a5mmvded75-64410fb0\", \"worker_id\": \"xv24a5mmvded75\", \"runpod_version\": \"1.3.4\"}",
    "executionTime": 376,
    "id": "sync-52c9160f-9210-4888-a6bb-66061ee27eb6-e1",
    "status": "FAILED"

**Comment by davefojtik** [comment]
Oops.. You're right. Our bot doesn't use img2img or inpainting yet so I forgot the other image file inputs! Will fix in a minute.
Also it seems like the Fooocus-API requires you to send "advanced_params" here.

**Comment by davefojtik** [comment]
Please rebuild the image with current code or use the new `3wad/runpod-fooocus-api:0.2.41` on the endpoint and let me know if it's working now. When I tried your example with "advanced_params" now, it did.

**Comment by kirrr21** [comment]
thank you! but still can't make it work for some reason, i guess i am trying wrong post body. do you have an example of working one? it would be awesome

**Comment by davefojtik** [comment]
Sure. Try this:
```json
{"input":{
    "api_name": "inpaint-outpaint2",
    "advanced_params": {},
    "require_base64": true,
    "input_image":"your-urlsafe-base64",
    "input_mask":"your-urlsafe-base64",
    "inpaint_additional_prompt": "prompt"
    }
}
```
Also, if you're doing the "New Release" image update on RunPod endpoint, don't forget to change worker count to 0 and than back to your number OR terminate nodes with old images one by one to force them to the newer version.

The errors are still present when I use img urls and probably on V1 endpoint though. I am hopefully going to fix all of this in the next update which should be the first full release aiming to cover 100% of the latest Fooocus-API

**Comment by kirrr21** [comment]
it works! thank you very much and looking forward to your first full release, you are awesome
