### ISSUE TITLE
typo... "inpait" instead of "inpaint"

### ISSUE THREAD

**Issue by aleph65** [davefojtik/RunPod-Fooocus-API#9]
Should be "inpaint" instead... can you fix?

e.g. /v2/generation/image-inpait-outpaint ---> /v2/generation/image-inpaint-outpaint

BTW, this is amazing, thanks so much!

**Comment by davefojtik** [comment]
Hello and thank you!
Not yet. This typo has been fixed just recently in the newest Fooocus-API [v0.3.30](https://github.com/konieshadow/Fooocus-API/releases/tag/v0.3.30), we're currently on **v0.3.29** (the compability is always stated in the [readme](https://github.com/davefojtik/RunPod-Fooocus-API/blob/main/README.md)). I am already working on the update though.

**Comment by aleph65** [comment]
Got it, thanks! BTW, got the serverless running perfectly, you are truly a legend. Thanks again :)

Small idea, during pod volume setup, we could have a quick script that makes all "types" of requests (ImagePrompt, CPDS, Outpaint, etc.) so those models download ahead of time with 1 click. I'll share if I write it

Your docs are super great too. Cheers!

**Comment by davefojtik** [comment]
Glad it's working! That idea sounds great. To help you a bit, this should be a list of all the default models required to run all endpoints: https://huggingface.co/3WaD/RunPod-Fooocus-API/tree/main/v0.3.30 (plus [juggernautXL](https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_version6Rundiffusion.safetensors) and [sd_xl_offset_example-lora_1.0](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_offset_example-lora_1.0.safetensors))
But I don't recommend using it as the download source (yet). Things can change there as it currently serves only a testing purpose for my experiments of turning this into a fully preinstalled standalone container image that would not need a network volume. Also, see the [Predownload and install](https://github.com/konieshadow/Fooocus-API?tab=readme-ov-file#predownload-and-install) part of Fooocus-API readme, or there's this part in Fooocus-API's [main.py](https://github.com/konieshadow/Fooocus-API/blob/074a956d2fc6e12e9b669cfe6611fd576dd7e315/main.py#L380):

```python
if load_all_models:
        import modules.config as config
        from fooocusapi.parameters import default_inpaint_engine_version
        config.downloading_upscale_model()
        config.downloading_inpaint_models(default_inpaint_engine_version)
        config.downloading_controlnet_canny()
        config.downloading_controlnet_cpds()
        config.downloading_ip_adapters()
    print("[Pre Setup] Finished")
```
That you could theoretically use. Let me know about the progress or if you'll have any questions.

**Comment by davefojtik** [comment]
Release [v0.3.30](https://github.com/davefojtik/RunPod-Fooocus-API/tree/268fc9b179f2d8583528bbd73a4d1fcb625a0d53) is out.
- Updated to Fooocus-API v0.3.30 - typo is fixed
- Changed the network setup flow. Now it uses custom CPU-only setup image that downloads all models and moves everything into the network volume. Effectively removes the step of manually going through endpoints.
- Now features "Standalone" branch and image that has all the models and files baked in. Can be used without network volume, check it out!

Thank you for your feedback! I am closing the issue for now. Let me know if you'll have more!

**Comment by aleph65** [comment]
Incredible, thank you Dave!
